services:

  Mooc.Courses.application.CourseCreator:
    class: ../../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: [ '@Mooc.Courses.domain.CourseRepository',  '@Mooc.shared.EventBus' ]

  Mooc.Courses.domain.CourseRepository:
    class: ../../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: [ '@Mooc.shared.ConnectionManager' ]

  Mooc.Courses.CreateCourseCommandHandler:
    class: ../../../../../../Contexts/Mooc/Courses/application/CreateCourseCommandHandler
    arguments: [ '@Mooc.Courses.application.CourseCreator' ]
    tags:
      - { name: 'commandHandler' }
