services:

  Mooc.courses.CourseRepository:
    class: ../../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: [ "@Mooc.shared.ConnectionManager" ]

  Mooc.Courses.application.CourseCreator:
    class: ../../../../../../Contexts/Mooc/Courses/application/CourseCreator
    arguments: [ '@Mooc.Courses.domain.CourseRepository' ]

  Mooc.Courses.domain.CourseRepository:
    class: ../../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: [ '@Mooc.shared.ConnectionManager' ]
