services:

  Mooc.Shared.MongoConfig:
    factory:
      class: ../../../../../../Contexts/Mooc/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Mooc.shared.ConnectionManager:
    factory:
      class: ../../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: [ 'mooc',  '@Mooc.Shared.MongoConfig' ]

  Mooc.shared.EventBus:
    class: ../../../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
    arguments: [ ]

  Mooc.shared.EventBus.DomainEventDeserializer:
    class: ../../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventDeserializer
    arguments: [ '@Mooc.shared.EventBus.DomainEventMapping' ]
