services:

  Mooc.shared.ConnectionManager:
    factory:
      class: ../../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: [ 'mooc' ]

  Mooc.shared.EventBus:
    class: ../../../../../../Contexts/Shared/infrastructure/EventBus/InMemoryAsyncEventBus
    arguments: [ ]

  Mooc.shared.EventBus.DomainEventDeserializer:
    class: ../../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventDeserializer
    arguments: [ '@Mooc.shared.EventBus.DomainEventMapping' ]
