imports:
  - { resource: ./application.yaml }

services:
  Mooc.shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/InMemory/InMemoryAsyncEventBus
    arguments: [ ]

  Mooc.EnvironmentArranger:
    class: ../../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: [ '@Mooc.shared.ConnectionManager' ]
